#!/bin/sh

# the first parameter is the name of the topic file.
# the second paramter if the top-k value

echo "Searching..."

# The path of the topic file
TOPIC=$1

# Convert the topics from TREC XML format to one query per line for JASSv2
JASSv2/atire/evaluation/trec2query $TOPIC t > queries.txt

# call JASS to do the search to 10 percent
JASSv2/JASSv1/jass queries.txt $2 52815 -d

# now copy the output to the output directory
cp ranking.txt /output/JASS_r4_10_percent.txt
