#!/bin/sh

# the first parameter is the name of the topic file.
# the second paramter if the top-k value

echo "Searching..."

# The path of the topic file
TOPIC=$1

# Convert the topics from TREC XML format to one query per line for JASSv2
JASSv2/atire/evaluation/trec2query $TOPIC t > queries.txt

# call JASS to do the search to completion
JASSv2/JASSv1/jass queries.txt $2 1000000000 -d

# now copy the output to the output directory
cp ranking.txt /output/JASS_c17_100_precent.txt

# call JASS to do the search to 10 percent
JASSv2/JASSv1/jass queries.txt $2 185566 -d

# now copy the output to the output directory
cp ranking.txt /output/JASS_c17_10_percent.txt

# call ATIRE to do the search to completion
JASSv2/atire/bin/atire -q queries.txt -k$2 -RBM25 -l$2 -et

# now copy the output to the output directory
cp ant.out /output/j2_ANT_c17_100_percent.txt

